[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "--failed-first"
testpaths = ["tests"]

[tool.coverage.run]
source = ["pyaerocom"]
omit = [
  # not used
  "pyaerocom/aeroval/utils.py",
  "pyaerocom/io/read_aeronet_invv2.py",
  "pyaerocom/io/read_aeronet_sdav2.py",
  "pyaerocom/io/read_aeronet_sunv2.py",
  "pyaerocom/io/read_gaw.py",
  "pyaerocom/io/read_aeolus_l2a_data.py",
  "pyaerocom/io/read_sentinel5p_data.py",
  "pyaerocom/io/readsatellitel2base.py",
  "pyaerocom/vert_coords.py",
]

[tool.coverage.report]
skip_covered = true
exclude_lines = [
  "pragma: no cover",
  "NotImplementedError",
  "abc.ABC",
  "if __name__=='__main__':",
  'if __name__=="__main__":',
  'if __name__ == "__main__":',
  "if __name__ == '__main__':",
]
