name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2.3.4
    - name: Set up Python ${{ matrix.python-version }}
      uses: s-weigand/setup-conda@v1.0.5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Conda info
      run: |
        conda --version
        which python
        python --version
    - name: New environment
      run: |
        conda create -n pya-ci -c conda-forge -f ./pyaerocom_env.yml
        conda activate pya-ci
    - name: Display current environments
      run: conda info --envs
    - name: Install pytest
      run: |
        conda install -c conda-forge --file ./test-requirements.txt
    - name: Install pyaerocom
      run: python ./setup.py install
    - name: Run pytest
      run: pytest --cov=pyaerocom/ --cov-report xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1.0.3
      with:
          file: ./coverage.xml
          flags: unittests
